### ISSUE TITLE
Missing a variable for the total number of steps

### ISSUE THREAD

**Issue by alexrobotics** [ethz-adrl/towr#17]
It will be better to have a variable "n_steps" to _directly_ specify the total number of steps, since it will be easier to tune the total number of steps according to different tasks, alongside with the open variable total time (T_total).

**Comment by awinkler** [comment]
Hi alex,

Yes, I removed this to show the user more directly what the algorithm requires, which is filling in the `params.ee_phase_durations_`  for each foot swing and stance.
https://github.com/ethz-adrl/towr/blob/93477a531bea8ffdf697b1932215acdb93044abe/towr/test/hopper_example.cc#L95

For now I suggest you just implement this on the your side as
```cpp
for (int i=0; i<n_steps; ++i)
  params.ee_phase_durations_.push_back(T/(2*n_steps)); // if only one foot
}
```
Also have a look at these classes, which were specifically designed for convenient initialization https://github.com/ethz-adrl/towr/blob/44c92450be6acd6b08470e6e2764f915c9946e8f/towr/include/towr/initialization/gait_generator.h#L46
