### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by eeoozz** [ethz-adrl/towr#18]
I was trying to install towr package (option 3: core library & GUI & ros-rviz-visualization). However, the build failed and following error message shows:

`/catkin_towr/src/towr/towr_ros/include/towr_ros/towr_xpp_ee_map.h:80:19: error: ‘foot_to_name’ is not a member of ‘xpp::biped’
       ee.second = xpp::biped::foot_to_name.at(id_biped);
`

`/catkin_towr/src/towr/towr_ros/include/towr_ros/towr_xpp_ee_map.h:86:19: error: ‘foot_to_name’ is not a member of ‘xpp::quad’
       ee.second = xpp::quad::foot_to_name.at(id_quad);`

It seems to be related with xpp library. My xpp version is `v1.0.6` installed with command line. Could anyone help with this? Thanks.

**Comment by awinkler** [comment]
Hi @eeoozz , thanks for pointing this out!
Yes, this is related to an update for xpp (v1.0.7) that hasn't yet made it to the binaries. I removed the dependency on this new xpp version, so pulling towr from master should fix this (see #19).

**Comment by eeoozz** [comment]
Thanks a lot for the help! It works now.
