### ISSUE TITLE
Rviz -  Fixed Frame [world] does not exist

### ISSUE THREAD

**Issue by randomuser007** [ethz-adrl/towr#27]
Hi,

I'm running on a fresh master install, all working fine, except the URDF's aren't appearing in Rviz as:
Global Status Warn - Fixed Frame: No tf data.  Actual error: Fixed Frame [world] does not exist.

And subsequently there is a status error for all robots (in rviz), as there is no transform to the non existent frame.

Reinstalled ipopt, ifopt, xpp and towr and rebuilt the ws but no change.

Any ideas?

Thanks!

**Comment by awinkler** [comment]
Hi! You have to run the optimization ('o') at least once so the URDFs are shown, did you do this?

Also, can you verify that rviz shows the frame "world" like here:
![selection_187](https://user-images.githubusercontent.com/4179579/42864877-3a8d167c-8a68-11e8-8146-898304f90700.png)

**Comment by randomuser007** [comment]
thanks for the quick reply.

I've optimised more than once, but still the same result, for all robot models.
![screenshot from 2018-07-18 18-15-57](https://user-images.githubusercontent.com/41092139/42872036-c38042bc-8ab6-11e8-8d8a-88425a87554e.png)

**Comment by awinkler** [comment]
Alright, hm...this could be related to http://wiki.ros.org/xpp. You can try installing this from github source, instead of the ros binaries. There should be a node that transforms the cartesian footholds you see visualized to the joint angles for the URDF:

![selection_190](https://user-images.githubusercontent.com/4179579/42879870-75ab17d4-8a92-11e8-833c-3281c7a62568.png)

**Comment by randomuser007** [comment]
That did it! Thanks for your help.

**Comment by awinkler** [comment]
So installing xpp through the ROS binaries `sudo apt-get install ros-kinetic-xpp` caused the problem? If you can give me a bit more detail, maybe I can fix that :-)

**Comment by randomuser007** [comment]
Yes it appears so. I purged ros-kinetic-xpp, then built xpp from source and now have no issues.  What details would you like?

**Comment by awinkler** [comment]
I see, alright, that at least tells me the newest version is working. That will make it into the binaries soon as well. Thanks.
