### ISSUE TITLE
How towr calculate the force？

### ISSUE THREAD

**Issue by littleggghost** [ethz-adrl/towr#3]
Hi, @awinkler 
Last time we talked about the dynamic simulation.
I notice that your achievement in latest paper is like the video by [Emo Todorov](http://homes.cs.washington.edu/~todorov/), University of Washington. The goal is also set up the initial condition and final condition and the optimizer will solve the motion planning, but the difference is that he used a kind of reinforcement learning algorithm. He used  a physics engine called [MuJoCo physics engine](http://www.mujoco.org/).
The well-known physics engine is like Bullet, ODE, Vortex, etc.  I read the **towr_core** and found lots of functions for dynamics. Could you tell me how to calculate the force except using the physics engine in **towr**?

**Comment by awinkler** [comment]
Hi! The dynamics (+ forces ) are enforced through constraints in the optimization problem. The keyword here is Trajectory Optimization, with shooting and direct methods. Here's an [overview](https://link.springer.com/chapter/10.1007/978-3-540-36119-0_4).
