### ISSUE TITLE
User-defined robot trajectory optimization

### ISSUE THREAD

**Issue by WoodenJin** [ethz-adrl/towr#30]
Sir, Thank for your excellent work.
I have just install towr package, but I try to use this package to control my own robot, how can I do it? is there any tutorial?
Thanks!

**Comment by awinkler** [comment]
Thanks! To define your own robot model for _towr_ to generate a motion for, add a robot with your kinematic and dynamic parameters. There is not tutorial at this point, but easy replicatable examples (monoped, biped, HyQ) here:
http://docs.ros.org/kinetic/api/towr/html/group__Robots.html

To simply visualize your robot as URDF, but using a motion-plan produced with one of the predefined robots in _towr_, see _xpp_: 
http://wiki.ros.org/xpp#Visualize_your_own_robot
