### ISSUE TITLE
Setting to Disallow Vertical Footholds?

### ISSUE THREAD

**Issue by kschultz1986** [ethz-adrl/towr#41]
I am noticing that with terrain featuring big step sizes (such as the "Block" terrain, at least with the "Biped" robot model), that the robot often picks footholds that are on the vertical edge of the step. This is unrealistic for many robots-- they would not be able to grip that vertical edge and pull themselves up by that one end effector, as what seems to be the case here. There should be a way to prevent the selection of such footholds completely.

Thank you for your important contribution to robotics.

**Comment by awinkler** [comment]
Hi @kschultz1986, 

Yes, you're right that sometimes these footholds might be hard to execute. However, physically a foothold on a vertical edge is feasible, as long as the force at this foothold is inside the now horizontally oriented friction cone. So using a foot to push horizontally off a vertical edge to generate some moment is a valid solution and imho should stay part of the search space.
If you want to prevent such footholds, or choose more conservative ones, you could add additional constraints on the slope of the terrain during stance. This would look similar to this https://github.com/ethz-adrl/towr/blob/189fd39b156d1ed80894c3d9086da1b8f7426de3/towr/src/terrain_constraint.cc#L66
except that you would constrain the slope of the terrain at the foothold xy position to be between e.g. -10 and +10 degrees. 

Cheers, Alex
