### ISSUE TITLE
Adaptation for serial robots

### ISSUE THREAD

**Issue by ahoarau** [ethz-adrl/towr#42]
This a very naive question, but would it be possible to adapt this library to a simple manipulator ?
Is it the point of the `monoped` robotModel ?

**Comment by awinkler** [comment]
Yes, i thought about this as well, that'd be very cool. This wasn't the intention of the monoped hopper though. However, the connection between the hopper and a 2-jointed-one-fingered gripper is there. The base for the finger would not need optimization variables, would be fixed, instead you could use the variables of the 6-dof floating base hopper to represent the object the finger is manipulating.
Similar a floating base quadruped robot = four-fingered gripper + manipulated 6D-object 
So I don't think it would be quite related and definetely possible to implement.
