### ISSUE TITLE
Cannot locate the nodes towr_user_interface, rviz_terrain_publisher, goal_pose_publisher and towr_ros_app

### ISSUE THREAD

**Issue by Rohithv-r** [ethz-adrl/towr#43]
Hello! 
When I run the (roslaunch towr_ros towr_ros.launch) command for the first time, only Rviz pops up. xterm doesn't open at all and it seems like ROS cannot locate the nodes (towr_user_interface, rviz_terrain_publisher, goal_pose_publisher and towr_ros_app). It shows the following error messages :  
ERROR: cannot launch node of type [towr_ros/towr_user_interface]: can't locate node [towr_user_interface] in package [towr_ros]
ERROR: cannot launch node of type [towr_ros/rviz_terrain_publisher]: can't locate node [rviz_terrain_publisher] in package [towr_ros]
ERROR: cannot launch node of type [towr_ros/goal_pose_publisher]: can't locate node [goal_pose_publisher] in package [towr_ros]
ERROR: cannot launch node of type [towr_ros/towr_ros_app]: can't locate node [towr_ros_app] in package [towr_ros]

I have made all the .cc files executable using the chmod command as well. Any ideas on how I can solve this issue?

**Comment by awinkler** [comment]
You don't have to make any .cc files executable. I suggest you install with 
`sudo apt-get install ros-<ros-distro>-towr_ros`
then don't forget to source your bashrc in the same terminal and run 
`roslaunch towr_ros towr_ros.launch`
Best of luck!

**Comment by Rohithv-r** [comment]
Oh right, it was a small issue! I ran "sudo apt-get install ros-kinetic-towr-ros" instead of "sudo apt-get install ros-kinetic-towr_ros". Thanks for the help, I'm a big fan of your work!
