### ISSUE TITLE
Weights for the costs are not taken into account.

### ISSUE THREAD

**Issue by Mathieu-Geisert** [ethz-adrl/towr#50]
Hi Alex,

In most place in the code, costs are defined as pair<CostName, weight> but it looks like weights are never taken into account (neither CostTerms nor NodeCosts take into account the weights) so it is quite misleading...
I've modified NodeCost to take into account the weights (see commit caca9b9a0b71388be1ec3bf5a956217302f60850 on my master branch), maybe it could be useful  to integrate this modification here.

Best,
Mathieu.

**Comment by Mathieu-Geisert** [comment]
Hi Alex,
The modifications of the CMakeLists are not necessary and are just added to make qtcreator loading the header files. I will create a new branch to de the pull request.
Best,
Mathieu.

**Comment by awinkler** [comment]
Fixed by #51
