### ISSUE TITLE
Not able to install towr using catkin build on ubuntu 14.04. " A required package was not found" error is coming.

### ISSUE THREAD

**Issue by neerajpal** [ethz-adrl/towr#57]
Errors     << ifopt:cmake /home/neeraj/leggedrobot/logs/ifopt/build.cmake.006.log
CMake Error at /usr/local/share/cmake-3.14/Modules/FindPkgConfig.cmake:457 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/FindPkgConfig.cmake:642 (_pkg_check_modules_internal)
  ifopt_ipopt/cmake/FindIPOPT.cmake:99 (pkg_check_modules)
  ifopt_ipopt/CMakeLists.txt:2 (find_package)

cd /home/neeraj/leggedrobot/build/ifopt; catkin build --get-env ifopt | catkin env -si  /usr/local/bin/cmake /home/neeraj/leggedrobot/src/ifopt --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX=/home/neeraj/leggedrobot/devel -DCMAKE_BUILD_TYPE=Release; cd -
...............................................................................
Failed     << ifopt:cmake             [ Exited with code 1 ]                   
Failed    <<< ifopt                   [ 0.3 seconds ]                          
Abandoned <<< towr                    [ Unrelated job failed ]                 
Abandoned <<< towr_ros                [ Unrelated job failed ]                 
[build] Summary: 0 of 3 packages succeeded.

**Comment by awinkler** [comment]
Make sure to install:
sudo apt-get install coinor-libipopt-dev

However, the IPOPT package for 14.04 has a bug, so it's better to install IPOPT manually for cmake to find.
