### ISSUE TITLE
How to specify number of steps per leg

### ISSUE THREAD

**Issue by mwchadwick1** [ethz-adrl/towr#58]
Hello,
I am generating motion for some quadrupeds and when I launch towr_ros the motion always consists of 4 steps and so is infeasible for long distance motions. I believe the step count comes from the size of ee_phase_durations_ but I`m not sure how/where I should be specifying this size.

**Comment by awinkler** [comment]
Yes. For convenience, the gait generator class fills these phase durations and allows looping though gaits using the "g" key. To add additional steps, e.g. _robot=Hyq, Gait=0_ in interface, add another _Walk2_ Stride here:

https://github.com/ethz-adrl/towr/blob/d30c4a06a86e8378ce5dea813071d0ef6d04070b/towr/src/quadruped_gait_generator.cc#L80
