### ISSUE TITLE
Difference between free_gait, dwl and towr+xpp?

### ISSUE THREAD

**Issue by littleggghost** [ethz-adrl/towr#59]
Hi, @awinkler 
AFAIK, [free_gait](https://github.com/leggedrobotics/free_gait), [dwl](https://github.com/robot-locomotion/dwl) and towr+xpp, there are some overlaps in these three projects. For example, they all has it's own rviz tools to monitor the robot states. 
So, I wonder if you familiar with the two other projs and know the difference with each other.
Hope your reply when you have a moment!

**Comment by awinkler** [comment]
Sure! These are all libraries for legged robot motion planning (and some visualization). Each of them uses different approaches to come up with the motion-plan. Some are more optimization focussed, others more directly translate the user input to a robot motion. They also vary in the model they use for planning (LIP, SRBD, RBD). Each has their corresponding paper, which helps if you want to know more. Best of luck! :)

**Comment by littleggghost** [comment]
Thanks for your prompt.
