### ISSUE TITLE
Specifying goal z position

### ISSUE THREAD

**Issue by mwchadwick1** [ethz-adrl/towr#61]
Hello,
Is there a way that I can specify a desired goal z position for the center of mass such that it is different from the initial z position? I see that in the towr user interface the page up and page down keys should shift the goal z position but they don't seem to have an effect. 
Thanks.

**Comment by awinkler** [comment]
Yes, you can add "Z" here:
https://github.com/ethz-adrl/towr/blob/e1b0e5ed7f0feed55c5ea62fa42fa9ac7c407985/towr/src/parameters.cc#L66
