### ISSUE TITLE
IPOPT's maximum cpu time is not reset when violated

### ISSUE THREAD

**Issue by orsoromeo** [ethz-adrl/towr#62]
Hi everyone,
I noticed that, whenever TOWR is not able to find a solution because the MAXIMUM_CPU_TIME is exceeded, this termination mode will keep on being triggered forever unless you restart TOWR. This means that if, for example, I attempt to optimize a solution for HyQ and the solver does not find a solution because of the maximum_cpu_time, then the solver won't find a solution even for the next formulations, even if I change robot, terrain or any other possible configuration. It really looks like the MAXIMUM_CPU_TIME flag of IPOPT is not properly reset and, when triggered, remains always ON. 
Please notice that this is probably an IPOPT bug, but I am wondering if anyone here noticed the same issue and found a fix for it.

**Comment by awinkler** [comment]
To avoid multiple discussions, let's discuss in the ifopt issue:
https://github.com/ethz-adrl/ifopt/issues/42
