### ISSUE TITLE
how can I add the CPG(central pattern generator) model into the code?

### ISSUE THREAD

**Issue by hejiayu1** [ethz-adrl/towr#63]
I want to compare the CPG and model-based approach and behavior-based approach.If I want to add the CPG model,which file should I modify？

**Comment by awinkler** [comment]
The CPG approach is very different from the Trajectory Optimization implemented by towr, so there is not much overlap of code. That means, unfortunately, a CPG approach cannot be easily implemented here.

**Comment by hejiayu1** [comment]
thanks
