### ISSUE TITLE
Rviz no tf data

### ISSUE THREAD

**Issue by benjamin1203** [ethz-adrl/towr#66]
Hi all , I had just picked up ROS recently for a project that I am currently working on regarding autonomous robots. So I was trying to get the mapping process going , I have with me a UPsqaured connected to a RPlidar A1 and I am accessing the UPsquared through my computer.  I launched the rplidar launch file first , then the gmapping launch file from another terminal. On the gmapping.launch terminal I got this error message :
[ WARN] [1577691725.782039473]: MessageFilter [target=odom ]: Dropped 100.00% of messages so far. Please turn the [ros.gmapping.message_notifier] rosconsole logger to DEBUG for more information.
I do not know how to solve this error and am stuck , please help.

**Comment by awinkler** [comment]
Hi @benjamin1203 , this doesn't seem to be related to towr, so I'm closing this here. You should be able to find some anwers on ros.org (related to rviz). Best of luck!
