### ISSUE TITLE
Integrating existing height map(Grid map) with Towr

### ISSUE THREAD

**Issue by SriDatta9** [ethz-adrl/towr#80]
Hi Alex, 
Firstly, Great work!
Could you please tell me how do I integrate grid map with Towr.

**Comment by awinkler** [comment]
Thanks! You'd have to write a wrapper for grid map that supplies the functions of this interface:

https://github.com/ethz-adrl/towr/blob/master/towr/include/towr/terrain/height_map.h

The main point is that whatever value of grid map you want to use, you'll have to supply the derivative of that value wrt the optimization variables.

**Comment by Akshay-9416** [comment]
Thank you for the response! Sure. I will do that.

**Comment by SriDatta9** [comment]
Thank you for the response! Surely, I will do that.

**Comment by prakharg01** [comment]
> Thank you for the response! Surely, I will do that.

Thanks for this, have you tried doing this?
